export interface Camera {
    id: string
    brand: string
    model: string
    fullName: string
    level: "beginner" | "intermediate" | "pro"
    plainEnglishDescription: string
    flatSetting: { plainEnglish: string; technical: string }
    availableProfiles: string[]
    technicalNotes: string
  }
  
  export const CAMERAS: Camera[] = [
    { id: "sony-zv-e10", brand: "Sony", model: "ZV-E10", fullName: "Sony ZV-E10", level: "beginner", plainEnglishDescription: "Great starter camera with interchangeable lenses. Colours look natural straight out of the box.", flatSetting: { plainEnglish: "Use 'Picture Profile 7' to keep your image flat and flexible for editing", technical: "PP7 S-Log2 or PP3 Cine" }, availableProfiles: ["Standard", "Neutral", "PP3 Cine", "PP7 S-Log2"], technicalNotes: "S-Log2 requires ISO 800 minimum." },
    { id: "sony-zv-e10-ii", brand: "Sony", model: "ZV-E10 II", fullName: "Sony ZV-E10 II", level: "beginner", plainEnglishDescription: "Upgraded starter camera with better low light and 4K. Same great Sony colour.", flatSetting: { plainEnglish: "Use 'S-Cinetone' for a cinematic look, or 'PP7' to keep colours flat for editing", technical: "S-Cinetone or PP7 S-Log2" }, availableProfiles: ["Standard", "S-Cinetone", "PP7 S-Log2", "PP8 S-Log3"], technicalNotes: "S-Cinetone gives pleasing skin tones with no grading needed." },
    { id: "sony-a7-iv", brand: "Sony", model: "A7 IV", fullName: "Sony A7 IV", level: "intermediate", plainEnglishDescription: "Professional full-frame camera. Excellent colours and very capable in low light.", flatSetting: { plainEnglish: "Use 'S-Log3' for maximum editing flexibility, or 'S-Cinetone' for a ready-to-use cinematic look", technical: "PP8 S-Log3/S-Gamut3.Cine" }, availableProfiles: ["Standard", "S-Cinetone", "PP7 S-Log2", "PP8 S-Log3"], technicalNotes: "Full-frame sensor gives shallower depth of field and better low light." },
    { id: "sony-fx3", brand: "Sony", model: "FX3", fullName: "Sony FX3", level: "pro", plainEnglishDescription: "Cinema camera in a small body. Used on professional film sets. Exceptional low light.", flatSetting: { plainEnglish: "Shoot in 'S-Log3' to capture the most detail in bright and dark areas", technical: "PP8 S-Log3/S-Gamut3.Cine, Cine EI mode" }, availableProfiles: ["S-Cinetone", "PP7 S-Log2", "PP8 S-Log3", "Cine EI"], technicalNotes: "Dual native ISO 800 and 12800." },
    { id: "sony-fx30", brand: "Sony", model: "FX30", fullName: "Sony FX30", level: "intermediate", plainEnglishDescription: "Cinema camera without the cinema price. Very popular with indie filmmakers.", flatSetting: { plainEnglish: "Use 'S-Log3' to get the most out of editing, or 'S-Cinetone' for a great look without editing", technical: "PP8 S-Log3, APS-C crop" }, availableProfiles: ["S-Cinetone", "PP7 S-Log2", "PP8 S-Log3"], technicalNotes: "APS-C gives a slightly tighter field of view than full-frame." },
    { id: "canon-r50", brand: "Canon", model: "EOS R50", fullName: "Canon EOS R50", level: "beginner", plainEnglishDescription: "Canon entry-level mirrorless. Warm and pleasing colours — great for people and portraits.", flatSetting: { plainEnglish: "Set 'Picture Style' to 'Flat' to keep your image flexible for editing", technical: "Picture Style: Flat" }, availableProfiles: ["Standard", "Portrait", "Neutral", "Flat"], technicalNotes: "Canon colours are warm by nature — great for skin tones." },
    { id: "canon-r8", brand: "Canon", model: "EOS R8", fullName: "Canon EOS R8", level: "beginner", plainEnglishDescription: "Full-frame Canon at an accessible price. Beautiful natural colours with great low light.", flatSetting: { plainEnglish: "Use 'Canon Log' or 'Flat' picture style for the most editing flexibility", technical: "Canon Log or Picture Style: Flat" }, availableProfiles: ["Standard", "Neutral", "Flat", "Canon Log"], technicalNotes: "Full-frame sensor gives excellent background blur." },
    { id: "canon-r6-ii", brand: "Canon", model: "EOS R6 Mark II", fullName: "Canon EOS R6 Mark II", level: "intermediate", plainEnglishDescription: "Professional Canon hybrid camera. Outstanding autofocus and cinema-quality video.", flatSetting: { plainEnglish: "Shoot in 'Canon Log 3' for maximum control in editing", technical: "Canon Log 3, Wide DR picture style" }, availableProfiles: ["Standard", "Flat", "Canon Log", "Canon Log 3"], technicalNotes: "Canon Log 3 has the best dynamic range for high-contrast scenes." },
    { id: "canon-c70", brand: "Canon", model: "Cinema EOS C70", fullName: "Canon Cinema EOS C70", level: "pro", plainEnglishDescription: "Professional cinema camera. The go-to for documentary and narrative indie films.", flatSetting: { plainEnglish: "Shoot in 'Canon Log 2' or 'Canon Log 3' — this camera is designed for log shooting", technical: "Canon Log 2 Cinema Gamut or Canon Log 3 BT.2020" }, availableProfiles: ["Canon Log 2", "Canon Log 3", "Wide DR"], technicalNotes: "Built-in ND filters. RF mount." },
    { id: "blackmagic-pocket-6k", brand: "Blackmagic", model: "Pocket Cinema 6K", fullName: "Blackmagic Pocket Cinema 6K", level: "pro", plainEnglishDescription: "Cinema camera loved by indie filmmakers worldwide. Shoots in RAW — gives you complete control in editing.", flatSetting: { plainEnglish: "Shoot in 'Blackmagic RAW' — this camera is built for maximum editing control", technical: "BRAW, Film mode, ISO 400 base" }, availableProfiles: ["Film", "Extended Video", "Video", "Blackmagic RAW"], technicalNotes: "Dual native ISO 400 and 3200." },
    { id: "sony-a6000", brand: "Sony", model: "A6000", fullName: "Sony A6000", level: "beginner", plainEnglishDescription: "One of the most popular beginner cameras ever made. Lightweight, affordable, and produces great images for its price.", flatSetting: { plainEnglish: "Set 'Picture Profile' to PP3 or PP4 for a flatter image that is easier to colour in editing", technical: "PP3 Cine1 or PP4 Cine2" }, availableProfiles: ["Standard", "Vivid", "Neutral", "PP3 Cine1", "PP4 Cine2"], technicalNotes: "No S-Log on A6000. PP3/PP4 give the most editing flexibility available on this body." },
  { id: "sony-a6400", brand: "Sony", model: "A6400", fullName: "Sony A6400", level: "intermediate", plainEnglishDescription: "Hugely popular APS-C camera known for its incredibly fast and accurate autofocus. A favourite for solo filmmakers.", flatSetting: { plainEnglish: "Use 'S-Log2' or 'S-Log3' to keep your image flat and give yourself maximum control when editing", technical: "PP7 S-Log2 or PP8 S-Log3, ISO 800 minimum" }, availableProfiles: ["Standard", "Neutral", "S-Cinetone", "PP7 S-Log2", "PP8 S-Log3"], technicalNotes: "Real-time Eye AF makes it ideal for solo shooting with no camera operator." },
  { id: "sony-a6700", brand: "Sony", model: "A6700", fullName: "Sony A6700", level: "intermediate", plainEnglishDescription: "Sony newest and most powerful APS-C camera. Incredible image quality, AI autofocus, and 4K 120fps slow motion.", flatSetting: { plainEnglish: "Use 'S-Log3' for maximum editing control, or 'S-Cinetone' for a beautiful cinematic look straight away", technical: "PP8 S-Log3/S-Gamut3.Cine, ISO 800 minimum" }, availableProfiles: ["Standard", "S-Cinetone", "PP7 S-Log2", "PP8 S-Log3"], technicalNotes: "Best APS-C Sony ever made. AI subject recognition autofocus. 4K 120fps available." },
  { id: "blackmagic-pocket-4k", brand: "Blackmagic", model: "Pocket Cinema 4K", fullName: "Blackmagic Pocket Cinema 4K", level: "intermediate", plainEnglishDescription: "Smaller and more affordable Blackmagic cinema camera. Incredible image quality for the price.", flatSetting: { plainEnglish: "Shoot in 'Blackmagic RAW' or 'Film' mode for maximum editing flexibility", technical: "BRAW or ProRes in Film mode" }, availableProfiles: ["Film", "Extended Video", "Video", "Blackmagic RAW"], technicalNotes: "MFT sensor. Pairs well with speedbooster." },
  { id: "dji-osmo-pocket-3", brand: "DJI", model: "Osmo Pocket 3", fullName: "DJI Osmo Pocket 3", level: "beginner", plainEnglishDescription: "Tiny camera with a built-in gimbal. Perfect for run-and-gun filming. Surprisingly cinematic.", flatSetting: { plainEnglish: "Use 'D-Log M' mode for more flexibility when editing, or shoot normal for a great ready-to-use image", technical: "D-Log M colour profile" }, availableProfiles: ["Normal", "D-Log M", "HLG"], technicalNotes: "1-inch sensor with built-in 3-axis stabilisation." },
  { id: "gopro-hero-12", brand: "GoPro", model: "Hero 12", fullName: "GoPro Hero 12", level: "beginner", plainEnglishDescription: "Action camera that shoots beautiful wide-angle footage. Great for POV and outdoor shots.", flatSetting: { plainEnglish: "Use 'Flat' colour profile to give yourself more control when editing", technical: "Flat colour profile, Linear lens" }, availableProfiles: ["Vivid", "Natural", "Flat", "Log"], technicalNotes: "HyperSmooth stabilisation. Linear lens removes fisheye distortion." },
  { id: "iphone-15-pro", brand: "Apple", model: "iPhone 15 Pro", fullName: "iPhone 15 Pro", level: "beginner", plainEnglishDescription: "The best smartphone camera ever made. Shoots ProRes and Log — genuinely cinematic in good light.", flatSetting: { plainEnglish: "Turn on 'Apple Log' in Camera settings for editing flexibility, or use 'Cinematic mode' for a beautiful ready-to-use look", technical: "Apple Log in ProRes" }, availableProfiles: ["Standard", "Cinematic", "Apple Log (ProRes)"], technicalNotes: "Apple Log only available in ProRes. Requires significant storage." },
  { id: "iphone-16-pro", brand: "Apple", model: "iPhone 16 Pro", fullName: "iPhone 16 Pro", level: "beginner", plainEnglishDescription: "Apple latest and most capable camera phone. Shoots 4K120 and has improved low light.", flatSetting: { plainEnglish: "Use 'Apple Log' in ProRes for editing flexibility, or 'Cinematic mode' for instant great results", technical: "Apple Log ProRes, 4K up to 120fps" }, availableProfiles: ["Standard", "Cinematic", "Apple Log (ProRes)"], technicalNotes: "Camera Control button adds hardware shutter." },
  { id: "fujifilm-xs20", brand: "Fujifilm", model: "X-S20", fullName: "Fujifilm X-S20", level: "intermediate", plainEnglishDescription: "Fujifilm colour science is legendary. Beautiful film simulations that look great without any editing.", flatSetting: { plainEnglish: "Use 'F-Log2' for editing flexibility, or pick 'Eterna Cinema' for a ready-to-use cinematic look", technical: "F-Log2 or Eterna Cinema film simulation" }, availableProfiles: ["Provia", "Velvia", "Eterna Cinema", "F-Log", "F-Log2"], technicalNotes: "Film simulations inspired by real Fujifilm film stocks." },
  { id: "fujifilm-xt5", brand: "Fujifilm", model: "X-T5", fullName: "Fujifilm X-T5", level: "intermediate", plainEnglishDescription: "Fujifilm flagship APS-C camera. 40MP stills and stunning video colour. A filmmaker favourite.", flatSetting: { plainEnglish: "Use 'Eterna Cinema' for a beautiful filmic look, or 'F-Log2' for maximum editing control", technical: "F-Log2 or Eterna Cinema, 6.2K open gate" }, availableProfiles: ["Provia", "Velvia", "Eterna Cinema", "F-Log", "F-Log2"], technicalNotes: "Best colour science in APS-C." },
  { id: "panasonic-g7", brand: "Panasonic", model: "Lumix G7", fullName: "Panasonic Lumix G7", level: "beginner", plainEnglishDescription: "Affordable beginner camera that punches above its weight for video. Great value for money.", flatSetting: { plainEnglish: "Set 'Photo Style' to 'Cinelike D' for a flat image that is easier to colour in editing", technical: "Cinelike D photo style" }, availableProfiles: ["Standard", "Vivid", "Natural", "Cinelike D", "Cinelike V"], technicalNotes: "4K at a very affordable price." },
  { id: "panasonic-s5-ii", brand: "Panasonic", model: "Lumix S5 II", fullName: "Panasonic Lumix S5 II", level: "intermediate", plainEnglishDescription: "Professional full-frame Panasonic. Exceptional video quality with phase-detect autofocus.", flatSetting: { plainEnglish: "Use 'V-Log' for maximum editing control, or 'Cinelike D2' for a great look without heavy editing", technical: "V-Log L, ISO 640 base" }, availableProfiles: ["Natural", "Cinelike D2", "Cinelike V2", "V-Log L", "HLG"], technicalNotes: "V-Log L has 14 stops of dynamic range." },
  { id: "om-system-om5", brand: "OM System", model: "OM-5", fullName: "OM System OM-5", level: "intermediate", plainEnglishDescription: "Weatherproof compact camera perfect for outdoor and documentary filmmaking. Goes anywhere.", flatSetting: { plainEnglish: "Use 'OM-Log400' for editing flexibility, or 'Flat' picture mode for a neutral starting point", technical: "OM-Log400 or Flat picture mode" }, availableProfiles: ["Natural", "Flat", "OM-Log400", "Vivid"], technicalNotes: "IP53 weather sealing. Up to 7.5 stops image stabilisation." }
]

// Sorted alphabetically by fullName
CAMERAS.sort((a, b) => a.fullName.localeCompare(b.fullName))

export function getCameraById(id: string): Camera | undefined {
  return CAMERAS.find(c => c.id === id)
}